---
- name: Fully provision a build server EC2 instance from scratch
  hosts: tag_Name_build_server
  become: yes
  become_method: sudo
  gather_facts: yes
  force_handlers: true
  any_errors_fatal: true

  roles:
    - bricebentler_com/s3_pre_existing_rpm
    - common
    - { role: hostname, hostname_prefix: 'bricebentler-build' }
    - linux_user_ec2_user
    - linux_user_nginx
    - postfix
    - rsa_keys
    - php/cli
    - composer
    - bricebentler_com/git
    - bricebentler_com/create_rpm

  handlers:
    - include: handlers/handlers.yml
