---
- name: Fully provision a bricebentler.com EC2 instance from scratch
  hosts: tag_Name_bricebentler_com
  become: yes
  become_method: sudo
  gather_facts: yes
  force_handlers: true
  any_errors_fatal: true

  roles:
    - common
    - hostname
    - linux_user_ec2_user
    - linux_user_nginx
    - postfix
    - rsa_keys
    - { role: nginx, pre_lets_encrypt: True }
    - php
    - composer
    - bricebentler_com/deploy
#    - lets_encrypt # TODO : Run this manually first. seeing issue: "ImportError: No module named cryptography.hazmat.bindings.openssl.binding"
#    - { role: nginx, pre_lets_encrypt: False }

  handlers:
    - include: handlers/handlers.yml
