---
- name: Fully provision a bricebentler.com EC2 instance from scratch
  hosts: tag_Name_bricebentler_com
  become: yes
  become_method: sudo
  gather_facts: yes
  force_handlers: true
  any_errors_fatal: true

  roles:
    - common
    - hostname
    - linux_user_ec2_user
    - linux_user_nginx
    - { role: nginx, pre_lets_encrypt: True }
    - php
    - lets_encrypt
    - { role: nginx, pre_lets_encrypt: False }
    - composer
    - postfix

  handlers:
    - include: handlers/handlers.yml
