---
- name: Create a bricebentler.com RPM package
  command: "{{ create_rpm_fpm_path }} --verbose -s dir -t rpm --rpm-use-file-permissions --rpm-user {{ nginx_user_name }} --rpm-group {{ nginx_group_name }} --description {{ bricebentler_com_git_tag }} -n {{ create_rpm_package_name }} -v {{ bricebentler_com_git_tag }} --directories {{ bricebentler_dir_name }} --prefix {{ bricebentler_parent_dir_path }} -a noarch -p {{ create_rpm_temp_path }} {{ bricebentler_dir_name }}"
  args:
    chdir: "{{ bricebentler_parent_dir_path }}/"
  become: yes
  become_user: "{{ nginx_user_name }}"
  become_method: sudo

# aws_s3 assumes that for PUTs, the file exists on the local provisioner (machine where you are running Ansible from).
# This is not the case for builds. The RPM exists on the build server.
- name: Put the RPM on AWS S3
  command: "/usr/bin/aws s3 cp {{ create_rpm_temp_path }} s3://{{ rpm_s3_bucket }}{{ rpm_s3_dir_path }}/{{ rpm_file_name }}"

- name: Delete the RPM from the build server
  file:
    state: absent
    path: "{{ create_rpm_temp_path }}"
