---
- name: Include secrets for bricebentler.com app
  include_vars: secrets.yml

- name: Remove previous installation of bricebentler.com application
  file:
    state: absent
    path: "{{ bricebentler_app_root }}"

- name: Clone bricebentler.com via git
  git:
    repo: "{{ bricebentler_com_git_repo }}"
    dest: "{{ bricebentler_app_root }}"
    clone: yes
    update: yes
    version: "{{ bricebentler_com_git_tag }}"
    accept_hostkey: true
    key_file: "{{ rsa_keys_bitbucket_path }}"

- name: Copy the env config file
  template:
    src: '.env.j2'
    dest: "{{ bricebentler_app_root }}/etc/.env"
    mode: 0640
    owner: "{{ nginx_user_name }}"
    group: "{{ nginx_group_name }}"

- name: Install composer packages for bricebentler.com
  composer:
    command: install
    working_dir: "{{ bricebentler_app_root }}"
    no_dev: yes
    optimize_autoloader: yes

- name: Remove unnecessary directories from project
  file:
    state: absent
    path: "{{ bricebentler_app_root }}/{{ item }}"
  with_items:
    - deploy
    - etc/.env.local
    - tests
    - .gitignore
    - composer.json
    - phpunit.xml
    - README.md
    - Vagrantfile

- name: Ensure the entire bricebentler.com application has correct permissions
  file:
    state: directory
    path: "{{ bricebentler_app_root }}"
    recurse: yes
    owner: "{{ nginx_user_name }}"
    group: "{{ nginx_group_name }}"
