---
lets_encrypt_certbot_url: 'https://dl.eff.org/certbot-auto'
lets_encrypt_logs_path: '/var/log/letsencrypt'
lets_encrypt_certbot_path: '/usr/bin/certbot-auto'
lets_encrypt_certs_path: '/etc/letsencrypt/live/bricebentler.com'
lets_encrypt_certs_dirname: dev.nwfapco.com
lets_encrypt_email_address: 'me@bricebentler.com'
lets_encrypt_domains_list:
  apex: 'bricebentler.com'
  www: 'www.bricebentler.com'
