version: 2

links:
  - &root
      ~/app

  - &env
    working_directory: *root
    docker:
      - image: circleci/node:10.12-browsers


jobs:

  setup-lambda-email-send:
    <<: *env
    steps:
      - checkout
      - restore_cache:
          keys:
            - lambda-email-send-npm-{{ .Branch }}
      - run:
          name: Install lambda deps
          command: |
            cd lambda/email-send
            npm install --quiet
      - save_cache:
          key: lambda-email-send-npm-{{ .Branch }}
          paths:
            - ~/app/lambda/email-send/node_modules
      - persist_to_workspace:
          root: *root
          paths:
            - .

  test-lambda-email-send:
    <<: *env
    steps:
      - attach_workspace:
          at: *root
      - restore_cache:
          keys:
            - lambda-email-send-npm-{{ .Branch }}
      - run:
          name: Run spec
          command: |
            cd lambda/email-send
            npm run test
      - run:
          name: Clear NPM dev dependencies
          command: |
            cd lambda/email-send
            rm -rf node_modules/*
            npm install --production --quiet
      - persist_to_workspace:
          root: *root
          paths:
            - .
