version: 2

links:
  - &root
      ~/app

  - &env
    working_directory: *root
    docker:
      - image: circleci/node:10.12-browsers

  - &cache_key
      lambda-email-send-npm--{{ checksum "~/app/lambda/email-send/package-lock.json" }}

  - &save_cache
    save_cache:
      key: *cache_key
      paths:
        - ~/app/lambda/email-send/node_modules

  - &restore_cache
    restore_cache:
      keys:
        - *cache_key


jobs:

  setup-lambda-email-send:
    <<: *env
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install lambda deps
          command: |
            cd lambda/email-send
            npm install --quiet
      - *save_cache
      - persist_to_workspace:
          root: *root
          paths:
            - .

  test-lambda-email-send:
    <<: *env
    steps:
      - attach_workspace:
          at: *root
      - *restore_cache
      - run:
          name: Run spec
          command: |
            cd lambda/email-send
            npm run test
      - run:
          name: Clear NPM dev dependencies
          command: |
            cd lambda/email-send
            rm -rf node_modules/*
            npm install --production --quiet
      - persist_to_workspace:
          root: *root
          paths:
            - .

  build-lambda-email-send:
    working_directory: *root
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: *root
      - run:
          name: Install Dependencies
          command: |
            apk add --no-cache py2-pip bash perl
            pip install awscli --upgrade

workflows:
  version: 2
  deploy-lambda-email-send:
    jobs:
      - setup-lambda-email-send
      - test-lambda-email-send:
          requires:
            - setup-lambda-email-send
