version: 2

links:
  - &root
      ~/app

  - &env
    working_directory: *root
    docker:
      - image: circleci/node:10.12-browsers


jobs:

  build:
    <<: *env
    steps:
      - checkout
      - run: |
          cd ~
          ls -lah
          pwd
          ls -lah app
          echo ${S3_BUCKET}
          echo $S3_BUCKET
