version: 2

links:
  - &root
      ~/app

  - &env
    working_directory: *root
    docker:
      - image: circleci/node:10.12-browsers


jobs:

  build:
    <<: *env
    steps:
      - checkout
      - run:
          name: Install lambda deps
          command: |
            cd lambda/email-send
            npm install
            ls -lah

