version: 2

defaults: &defaults
  working_directory: ~/app

jobs:

  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: |
          cd ~
          ls -lah
          pwd
          ls -lah app
          echo ${S3_BUCKET}
          echo $S3_BUCKET
