---
- name: Load postfix secrets
  include_vars: secrets.yml

- name: Install postfix packages
  yum:
    state: present
    name: "{{ item }}"
  with_items:
    - postfix
    - mailx

- name: Stop the sendmail service
  service:
    state: stopped
    name: sendmail
    enabled: no

- name: Start the postfix service
  service:
    state: started
    name: postfix
    enabled: yes

- name: Configure postfix
  template:
    src: main.cf.j2
    dest: "{{ postfix_configs_path }}/main.cf"
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload Postfix

- name: Add the postfix sasl passwd
  template:
    src: sasl_passwd.j2
    dest: "{{ postfix_sasl_passwd_path }}"
    mode: '0600'
    owner: root
    group: root
  register: postfix_sasl_passwd_output

- name: Update the postfix hash tables
  command: "/usr/sbin/postmap {{ postfix_sasl_passwd_path }}"
  args:
    chdir: "{{ postfix_configs_path }}"
  when: postfix_sasl_passwd_output.changed
  notify:
    - Reload Postfix

- name: Create the postfix SSL directory
  file:
    state: directory
    path: "{{ postfix_ssl_path }}"
    mode: '0755'
    owner: root
    group: root

- name: Add the SendGrid certificate authority bundle
  copy:
    src: gd_bundle-g2-g1.crt
    dest: "{{ postfix_sendgrid_cert_path }}"
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload Postfix
