---
- name: Install pre-req packages
  yum:
    state: present
    name: "{{ item }}"
  with_items:
    - augeas-libs
    - dialog
    - gcc
    - libffi-devel
    - openssl-devel
    - system-rpm-config

- name: Ensure the log directory exists
  file:
    state: directory
    path: "{{ lets_encrypt_logs_path }}"
    mode: 0755
    owner: root
    group: root

- name: Download certbot
  get_url:
    url: "{{ lets_encrypt_certbot_url }}"
    dest: "{{ lets_encrypt_certbot_path }}"
    mode: 0755
    owner: root
    group: root
