---
application_logs_path: '/var/log/www'

bricebentler_parent_dir_path: '/var/www'
bricebentler_dir_name: 'html'
bricebentler_app_root: "{{ bricebentler_parent_dir_path }}/{{ bricebentler_dir_name }}"
bricebentler_docroot: "{{ bricebentler_app_root }}/docroot"

composer_bin_path: '/usr/bin/composer'

lets_encrypt_certs_path: '/etc/letsencrypt/live/bricebentler.com'

logrotate_configs_path: '/etc/logrotate.d'

nginx_group_name: 'nginx'
nginx_home: '/var/lib/nginx'
nginx_user_name: 'nginx'

php_fpm_sockets_path: '/var/run/php-fpm'
php_fpm_bricebentler_socket_file: "{{ php_fpm_sockets_path }}/bricebentler.socket"

rpm_s3_bucket: 'bricebentler-db-dumps'
rpm_s3_dir_path: '/bricebentler_com_rpms'
rpm_file_name: "bricebentler-{{ bricebentler_com_git_tag }}-noarch.rpm"

rsa_keys_bitbucket_path: "{{ nginx_home }}/.ssh/bitbucket"
