---
- name: Create a build server EC2 instance
  ec2:
    state: present
    key_name: BricePersonalAWS
    instance_type: t2.nano
    image: "{{ ec2_instance_ami_id_build_server }}"
    wait: yes
    wait_timeout: 360
    group_id: "{{ ec2_instance_sec_group_ids_build_server }}"
    count: 1
    vpc_subnet_id: "{{ ec2_instance_subnet_id_build_server }}"
    assign_public_ip: yes
    monitoring: no
    instance_profile_name: "{{ ec2_instance_iam_role_build_server }}"
    instance_tags:
      Name: 'build-server'
      config_management: 'ansible'
    volumes:
      - device_name: /dev/xvda
        snapshot: "{{ ec2_instance_root_snap_id_build_server }}"
        volume_type: gp2
        volume_size: 8
        delete_on_termination: true
  register: create_ec2_instance_output

- name: Wait for SSH to come up
  wait_for:
    state: started
    host: "{{ item.public_dns_name }}"
    port: 22
    timeout: 300
    delay: 45
  with_items: "{{ create_ec2_instance_output.instances }}"
