---
- include_vars: roles/php/fpm/defaults/main.yml

- name: Install PHP packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_packages|difference(['php71-fpm', 'php71-opcache']) }}"

- include: configure/php.yml
