---
- name: Create a bricebentler.com EC2 instance
  ec2:
    state: present
    key_name: BricePersonalAWS
    instance_type: t2.nano
    image: "{{ ec2_instance_ami_id }}"
    wait: yes
    wait_timeout: 360
    group_id: "{{ ec2_instance_sec_group_ids }}"
    count: 1
    vpc_subnet_id: "{{ ec2_instance_subnet_id }}"
    assign_public_ip: yes
    monitoring: no
    instance_tags:
      Name: 'bricebentler.com'
      config_management: 'ansible'
    volumes:
      - device_name: /dev/xvda
        snapshot: "{{ ec2_instance_root_snap_id }}"
        volume_type: gp2
        volume_size: 8
        delete_on_termination: true
  register: create_ec2_instance_output

- name: Allocate a new EIP and attach to the EC2 instance
  ec2_eip:
    device_id: "{{ item.id }}"
  with_items: "{{ create_ec2_instance_output.instances }}"
  register: create_eip_output

- name: Output the Elastic IPs
  debug:
    msg: "Allocated Elastic IP: '{{ item.public_ip }}'"
  with_items: "{{ create_eip_output.results }}"

- name: Set fact containing EC2 instance public DNS
  set_fact:
    create_ec2_instance_public_dns: "ec2-{{ create_eip_output.results[0].public_ip|replace('.', '-') }}.us-west-2.compute.amazonaws.com"

- name: Create DNS record for www.bricebentler.com
  route53:
    state: present
    zone: bricebentler.com
    record: www.bricebentler.com
    type: CNAME
    ttl: "{{ ec2_instance_dns_ttl }}"
    value: "{{ create_ec2_instance_public_dns }}"
    wait: yes

- name: Create DNS record for bricebentler.com
  route53:
    state: present
    zone: bricebentler.com
    record: bricebentler.com
    type: A
    ttl: "{{ ec2_instance_dns_ttl }}"
    value: "{{ create_eip_output.results[0].public_ip }}"
    wait: yes

- name: Wait for SSH to come up
  wait_for:
    state: started
    host: "{{ item.public_ip }}"
    port: 22
    timeout: 300
  with_items: "{{ create_eip_output.results }}"
